substitutions:
  device_name: Test status screen
  device_id: test-screen
  # Home assistant sensors
  # Weather conditions
  weather_conditions: weather.forecast_zi_zhai
  # Outdoor sensors
  outdoor_temperature: weather.forecast_zi_zhai
  outdoor_humidity: weather.forecast_zi_zhai
  outdoor_rainfall: sensor.outdoor_rainfall
  aircon_power: sensor.plug_mini_jp_c43a_power
  # Indoor sensors
  indoor_temperature: sensor.co2_unit_scd40_temperature
  indoor_humidity: sensor.co2_unit_scd40_humidity
  indoor_pressure: sensor.indoor_pressure
  indoor_co2: sensor.co2_unit_scd40_carbon_dioxide
  # Media player
  ht_a9: media_player.ht_a9_3
  apple_tv: media_player.rihinkurumu
  foobar2k: media_player.foobar2000
  # AirCon status
  aircon: climate.eakon_remo_lapis
  # PC monitor status
  oled_monitor: switch.oledmonita_switch
  # Ceiling light status
  living_light: light.sirinkuraito_light

web_server:

# Include main functionality file
<<: !include .screen_base.yaml
